### ISSUE TITLE
Source code download for 2.2.1

### ISSUE THREAD

**Issue by awsaunier** [RedhawkSDR/redhawk#14]
Hi, I am looking for the source code for the 2.2.1 release.  I download both the Source-code zip and tar and the file that is download has no files within it.  The only fires in it is an image, copyright and release notes.  Also the directions provided to download and build the source code is wrong.  I tried the formula provided for 2.2.1 with no luck: `wget https://github.com/RedhawkSDR/redhawk/releases/download/<version>/redhawk-src-<version>.tar.gz`

Page that I found this link: https://github.com/redhawksdr/redhawk/releases/tag/2.2.1
Link that I downloaded with: https://github.com/RedhawkSDR/redhawk/archive/2.2.1.tar.gz
Link to download and build documentation: https://redhawksdr.github.io/Documentation/mainap4.html

**Comment by timcardenuto** [comment]
Yeah, the link  https://github.com/RedhawkSDR/redhawk/archive/2.2.1.tar.gz gives you the tar of the repo https://github.com/RedhawkSDR/redhawk  -  that repo is a "submodule" repo and it doesn't seem like the tar archives recursively grab the source from the sub-repos.  Not sure if that's a "bug" but anyway the right source tarball is the one with the release date as well, in this case called `redhawk-src-2.2.1-201812031407.tar.gz`. The link is https://github.com/RedhawkSDR/redhawk/releases/download/2.2.1/redhawk-src-2.2.1-201812031407.tar.gz

Unfortunately it's not very conducive to scripting/guessing since you need the release date...

**Comment by shmahon** [comment]
The `redhawk-src-X.X.X-<datestamp>.tar.gz` file has been renamed as specified in the REDHAWK Manual: `redhawk-src-X.X.X.tar.gz`. All future releases will maintain this naming scheme moving forward.

The "Source code" zip and tar files that Github puts on the release page is autogenerated. Github does not correctly process submodule repositories. Therefore these files will always be empty. 

Thank you for bringing this to our attention.
