### ISSUE TITLE
Improve SourceVITA49  to support low sampling rate (i.e. 8kHz, 800Hz)

### ISSUE THREAD

**Issue by James-Wang-JM** [RedhawkSDR/redhawk#26]
Launch waveform vita49_loopback_demo in sandbox, delete the dataFloat link between SigGen and SinkVITA49, create a dataShort link between SigGen and SinkVITA49, start the waveform, change the frequency of SigGen to 100Hz,  plot port data from dataShort_out of SourceVITA49. Now it starts plotting the signal in time domain.

Change the sample_rate of SigGen to 8kHz or 800Hz, observe the plotting window, it's blank and no signal exists.

Change the sample_rate of SigGen to 80kHz, observe the plotting window, the signal is back again.

**Comment by RedhawkDeployer** [comment]
Since the sample rate is so low, you are waiting for the internal buffers to fill before sending to the plot interface. For low rate signal you will need to reduce the SourceVITA49's advanced_configuration::buffer_size and advanced_configuration::corba_transfersize properties. For lower rate signals, recommend a .25 second buffer size, and assigned that value to both properties.
