### ISSUE TITLE
Install problem

### ISSUE THREAD

**Issue by joe-cavalry** [RedhawkSDR/redhawk#4]
**operating system:**
CENTOS 7.4

**command:**
sudo yum groupinstall "REDHAWK Development"

**error:**
File "/bin/yum", line 29, in <module>
    yummain.user_main(sys.argv[1:], exit_code=True)
  File "/usr/share/yum-cli/yummain.py", line 370, in user_main
    errcode = main(args)
  File "/usr/share/yum-cli/yummain.py", line 276, in main
    return_code = base.doTransaction()
  File "/usr/share/yum-cli/cli.py", line 693, in doTransaction
    if self.gpgsigcheck(downloadpkgs) != 0:
  File "/usr/share/yum-cli/cli.py", line 820, in gpgsigcheck
    self.getKeyForPackage(po, lambda x, y, z: self.userconfirm())
  File "/usr/lib/python2.7/site-packages/yum/__init__.py", line 6237, in getKeyForPackage
    keys = self._retrievePublicKey(keyurl, repo)
  File "/usr/lib/python2.7/site-packages/yum/__init__.py", line 6115, in _retrievePublicKey
    msg = _('Retrieving key from %s') % keyurl
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 19: ordinal not in range(128)

**Comment by eleaver** [comment]
I have the same problem. Simplified, it also occurs with just
yum install redhawk

Interestingly, the problem persists with most other usages of yum -- unrelated to redhawk -- until I disable /etc/yum.repos.d/redhawk. So the problem *might* be related to bad (e.g. unicode rather than ascii) metadata being retrieved from the repo, rather than an issue with the rpms themselves.

Saw the same behavior with redhawk 2.0.8, again on Centos 7.4.

If these installs work on CentOS 7.3, perhaps we should check if there was a yum regression between 7.3 and 7.4

**Comment by eleaver** [comment]
So here's a workaround hack: edit your /etc/yum.repos.d/redhawk.repo and set
1. enabled=1
2. gpgcheck=0
3. #gpgkey=file:///etc/pki/rpm−gpg/RPM−GPG−KEY−redhawk

i.e., disable gpgcheck AND comment out the path to the redhawk key file. As workaround hacks go, this is egregiously flaky and insecure. But it might float your boat off the reef.

**Comment by maxrobert** [comment]
It looks like you are cut-and-pasting step 3 from section 2.2.2.2 of the REDHAWK Manual PDF. Investigating your issue showed that the '-' characters in the gpgkey file name were not rendered as simple ascii dashes but as unicode hyphens. Thus, when yum goes to read the GPG key, it chokes on the unicode character in the filename. Since the GPG file gets installed in /etc/pki/rpm-gpg with the right name, you can just copy that filename into your /etc/yum.repos.d/redhawk.repo file.

The web-rendered REDHAWK Manual at http://redhawksdr.github.io/Documentation/mainch2.html#x4-90002.2 does _not_ exhibit the same problem and can be successfully cut-and-pasted into a {{redhawk.repo}} file.

The REDHAWK Manual will be updated to address the unicode character problem.
