### ISSUE TITLE
Failed to satisfy device dependencies for component - Waveform loading on Taget board

### ISSUE THREAD

**Issue by Nayanacyient** [RedhawkSDR/redhawk#46]
Hi,

I have the meta-redhawk-sdr(Branch : Pyro) with Yocto BSP am57xx and loaded image on Target board.

Loaded image has all the Redhawk components and basic Waveform.
Now trying to launch one of the available basic waveform from the image loaded on Taget board(Phytec).

Procedure or Fallowed steps:
1. Target board connected to Desktop server via serial cable and VLAN also available.
2. Started Domain and Device manager with naming services on Target board.
3. Connected to sandbox from python script as shown below :

**[redhawk@2a23bdd8bb78 ~]$ python**
Python 2.6.6 (r266:84292, Aug 18 2016, 15:13:37) 
[GCC 4.4.7 20120313 (Red Hat 4.4.7-17)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> from ossie.utils import redhawk,sb

>>> import time

>>> dom = redhawk.attach("REDHAWK_DEV")

>>> app = createApplication("/waveforms/rh/basic_components_demo/basic_components_demo.sad.xml")
Traceback (most recent call last):

  File "<stdin>", line 1, in <module>
NameError: name 'createApplication' is not defined

>>> app = dom.createApplication("/waveforms/rh/basic_components_demo/basic_components_demo.sad.xml")
Traceback (most recent call last):

  File "<stdin>", line 1, in <module>
  File "/usr/local/redhawk/core/lib/python/ossie/utils/redhawk/core.py", line 1794, in createApplication
    app = app_factory.create(name, initConfiguration, [])
  File "/usr/local/redhawk/core/lib/python/ossie/cf/cf_idl.py", line 2026, in create
    return _omnipy.invoke(self, "create", _0_CF.ApplicationFactory._d_create, args)

ossie.cf.**CF.CreateApplicationError: CF.ApplicationFactory.CreateApplicationError(errorNumber=CF_ENOSPC, msg="Failed to satisfy device dependencies for component:** 'rh.SigGen' with component id: 'SigGen_sine:rh.basic_components_demo_339_120418450_1'")

**Understanding from source:**

- As seen in the source or ***.spd.xml file**, observed PROCESSOR name is playing major role with respect to Target boards(cross compiled OS).

- My requirement for Target board is MACHINE_NAME=am57xx-phycore-rdk and **PROCESSOR=armv7l**

- I have mentioned both variables in  conf/local.conf.

- But few of the components only showing **armv7l implementation** like dsp, rbdsdecoder , device and domain manager spd.xml files. 

- All other components are with armv7ahf-neon processor implementation.

Can any one suggest how to change processor name from **armv7ahf-neon to armv7l** during the **building image**

If my observations are wrong as per above Error: can you suggest the solution for **Failed to satisfy device dependencies for component**

Regards,
Nayana

**Comment by Nayanacyient** [comment]
Hi, 

Please find attachment for the reference (Target board terminal).

[waveform_launch.odt.zip](https://github.com/RedhawkSDR/redhawk/files/5646761/waveform_launch.odt.zip)

**Comment by btgoodwin** [comment]
This group is not responsible for maintaining meta-redhawk-sdr.  Please feel free to submit this issue to our issues list.

That said, the `pyro` branch uses a much older attempt at patching a processor name into place at build-time by setting the `REDHAWK_PROCESSOR` value at the global level (a .conf file) as indicated in the [README.md](https://github.com/Geontech/meta-redhawk-sdr/tree/pyro#getting-started).  This method was later abandoned in favor of a script relying on `redhawk-codegen-native` to dynamically patch the XML files to match the various other patches that have to be applied to the core framework source code so that the build-time and run-time environments are guaranteed to match (especially on devices where this value is read from the CPU's registers rather than from source files).

**Comment by Nayanacyient** [comment]
Hi Thomas Goodwin,

Okay, i will post the same question on meta-redhawk-sdr group.


Regards,
Nayana
